//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int id_pedido { get; set; }
        public int id_carro_compra { get; set; }
        public string fecha { get; set; }
        public string estado { get; set; }
        public int codigo_carro { get; set; }
        public int total_precio { get; set; }
        public string hora { get; set; }
    
        public virtual Carro_Compra Carro_Compra { get; set; }
    }
}
